#!/bin/bash

SERIAL_FILE=~/.fcu_serial

if [[ -f $SERIAL_FILE ]]; then
    FCU_SERIAL=$(cat $SERIAL_FILE)
else
    echo "ERROR: $SERIAL_FILE does not exist."
    echo "Run the following command on the correct serial port to save the FCU's SN:"
    echo "  SERIAL_ID=\$(udevadm info /dev/ttyACM0 | awk -F \"[ =]\" '/ID_SERIAL_SHORT/ { print \$3 }')"
    echo "  echo \$SERIAL_ID > $SERIAL_FILE"
    exit 1
fi

./teensy_loader_cli --mcu=imxrt1062 --sn=$FCU_SERIAL -w -s -v fcu_firmware.hex
